### ISSUE TITLE
送信ボタン押下後、TypeError発生

### ISSUE THREAD

**Issue by yochan-Lab11** [yochan-Lab11/ordersystem#1]
送信ボタン押下後、なぜかTypeErrorが出てしまう。

**Comment by keinstn** [comment]
@yochan-Lab11 
github pages の公開ありがとうございます。こちらで試してみましたが、自分の環境では TypeError は再現しませんでした。やはり Failed to send message Error: LiffId is not found. のエラーが発生します。

自分の実施手順は以下です。

 - 使用したブラウザ
   - PC : chrome, safari
   - iPhone : LINE から開いたブラウザ
 
- 確認手順
  -  https://yochan-lab11.github.io/ordersystem/ を開く
  - あ、あ、あ、空欄で入力して送信ボタンをクリックする

エラーが発生した時の画面キャプチャを添付します。

**Safari の画面キャプチャ**
<img width="784" alt="スクリーンショット 2023-12-22 7 48 56" src="https://github.com/yochan-Lab11/ordersystem/assets/20488926/534ce198-f802-49e3-b2cc-f8787171fa87">

**iPhone の LINE から開いたブラウザの画面キャプチャ**
<img width="414" alt="smartphone" src="https://github.com/yochan-Lab11/ordersystem/assets/20488926/d453a2b4-5782-4963-999d-8cc62312599c">

**Comment by keinstn** [comment]
@yochan-Lab11 
TypeError とは関係がないかも知れませんが、Failed to send message Error: LiffId is not found. のエラーが発生した時に以下の点が気になりました。

デベロッパーツールの Console タブに `initializeApp` の ReferenceError が表示されていました。
コードを見る限りですと `initializeApp` の定義が無いようなのですが、これは liff SDK からインポートされる関数ということでしょうか？
https://github.com/yochan-Lab11/ordersystem/blob/main/index.html#L121

**Comment by yochan-Lab11** [comment]
@keinstn 
liff SDKにある関数だと思います。そのあたりの記述はサンプルコードをもとに記述しているので問題はない想定でいます。
原因は未だに不明でありますね。送信時エラー起きることは同じタイミングかと。
当時、睨んでいたのはtextareaとinputのタグ違いによりデータの型が変わってしまう？などを睨んでいました。
慌てて修正をかけましたが同エラーが起きておりました。

**Comment by keinstn** [comment]
@yochan-Lab11 
本件ですが、エラーの原因がわかりました。submit した時にイベントの伝播をストップしていなかったことが原因で TypeError が発生していたようです。

吉村さんが追加修正されていたようですので、まず https://github.com/yochan-Lab11/ordersystem/commit/418750cec6437f1b9ed28b4b1ef1706ec8296941 で https://github.com/yochan-Lab11/ordersystem/commit/9fb522bbd9b6c4f59dc7c9dbe32baa9594367cb6 にロールバックした後、以下の修正を入れました。

https://github.com/yochan-Lab11/ordersystem/commit/55bc084a38ed8681ba740417960b903bdbc627c9

その後 TypeError が出なくなったことを確認しました。こちらのミスで失礼しました。

なお、TypeError の原因はググったらすぐ出てきました。。。
[Liff.sendmessagesで「Failed to send message TypeError:キャンセルしました」発生](https://www.line-community.me/ja/question/60a5345a851f7443b473c7a3/liffsendmessages%E3%81%A7failed-to-send-message-typeerror%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F%E7%99%BA%E7%94%9F)

**Comment by yochan-Lab11** [comment]
エラー対応済みのため、クローズいたします。大変ありがとうございました。
また、今後の教訓にもしておきましょう。
