### ISSUE TITLE
氏名の下に電話番号のフォーム欄を足したい

### ISSUE THREAD

**Issue by yochan-Lab11** [yochan-Lab11/ordersystem#18]
新たに要望があり、電話番号も欲しくなったようです。
ハイフンは有り無し指定されてないので、一旦数字のみ入力できるフォーム欄追加をお願いできますでしょうか。
必須入力で良いかと思います。送信データにも乗せていただいてください。

**Comment by keinstn** [comment]
@yochan-Lab11 
電話番号について承知しました。フォーム欄はどの位置に追加したら良いでしょうか？

**Comment by yochan-Lab11** [comment]
> @yochan-Lab11 
> 
> 電話番号について承知しました。フォーム欄はどの位置に追加したら良いでしょうか？

@keinstn 
氏名欄の下に配置したいそうです。

**Comment by keinstn** [comment]
@yochan-Lab11 
[feature/18](https://github.com/yochan-Lab11/ordersystem/tree/feature/18) ブランチで氏名欄の下に電話番号の入力項目を追加する修正を行いました。

[feature/16](https://github.com/yochan-Lab11/ordersystem/tree/feature/16) の確認を頂いているところですが、問題なければ feature/16 と feature/18 をmaster ブランチにマージしますが、いかがいたしましょうか？

**Comment by yochan-Lab11** [comment]
@keinstn 
ご対応ありがとうございます！

masterブランチにマージお願い致します。
GAS側も対応させるようにしておきます。

**Comment by keinstn** [comment]
@yochan-Lab11 
main ブランチにマージしました！お手数ですが、GitHub Pages へのデプロイをお願いいたします。

**Comment by yochan-Lab11** [comment]
@keinstn 
ありがとうございます！デプロイしました。

**Comment by keinstn** [comment]
@yochan-Lab11 
ご対応ありがとうございました！
