### ISSUE TITLE
ユーザーからの追加要望

### ISSUE THREAD

**Issue by keinstn** [yochan-Lab11/ordersystem#2]
ユーザーから以下の追加要望があった

 - 商品名プルダウン　
 - 複数商品（弁当名）を一括注文
   - 「大盛」「小盛」表示ができればほしい（※現状は備考欄からとってます）
 - 会社・施設名
 - 部署名（ない場合は「なし」とご入力ください）　
（例：「〇階〇番窓口」「〇〇課〇階」など）
 - 受取日

備考欄も足したいそうです。
【注意事項】
・定休日：土日祝
・お弁当1つ税込み５００円です
・ご注文後のキャンセルは全額いただきます
・天候や交通事情等によりお届け希望時間に沿えない可能性もございますのであらかじめご了承ください。

**Comment by keinstn** [comment]
@yochan-Lab11 
作業中ですが、こちらの issue の修正のPRを作成しました。
https://github.com/yochan-Lab11/ordersystem/pull/3

[22b65d6](https://github.com/yochan-Lab11/ordersystem/commit/22b65d6705927b08ea5a93a245bdb50fe32b4008) で以下の項目を追加しました。

 - 会社・施設名
 - 部署名
 - 受取日
 - 注意事項

画面イメージは以下です。
![feature_2](https://github.com/yochan-Lab11/ordersystem/assets/20488926/6bfeddbe-3b3e-4adb-9638-a44ff278c2b7)

残項目の以下は要件が決まりましたらPRに追加します。

 - 商品名プルダウン　
 - 複数商品（弁当名）を一括注文

**Comment by yochan-Lab11** [comment]
@keinstn 
こちらもご対応いただけておりますので、クローズにします。
複数一括選択は組み合わせの数が増えて入力も大変になるので、１種類１送信でこのまま行こうと思います。
もし先方がどうしてもということであればリオープンで進めていきましょう。
