### ISSUE TITLE
その他アレンジ要望

### ISSUE THREAD

**Issue by yochan-Lab11** [yochan-Lab11/ordersystem#5]
@keinstn 
ユーザーさんからの要望ではないですが、仕上げ段階にもなりましたので
デザインも改良しました。という感じにはしておこうと思います。いわゆる吉村のリクエストです。
以下、ご対応いただけたり可能でしょうか。

①背景に御膳系の写真を差し込んで、フォームを透かしにしてみる。
②タイトル「お弁当ご注文フォーム」のテキストを入れ込み、背景色をつける。

イメージを添付しておきますのでご参考にしてください。
![キャプチャ](https://github.com/yochan-Lab11/ordersystem/assets/150769599/a6ac03cd-d2cf-4dce-b75f-36d9d9cd7ddb)

**Comment by keinstn** [comment]
@yochan-Lab11 

> ①背景に御膳系の写真を差し込んで、フォームを透かしにしてみる。
> ②タイトル「お弁当ご注文フォーム」のテキストを入れ込み、背景色をつける。

上記対応しましたので、またご確認をお願いします。
背景の御膳系の写真はイメージ図と同じものを使用しました。こちらの画像で良いかの判断はできませんでしたので、必要に応じて適宜差し替え下さい。

![feature_5](https://github.com/yochan-Lab11/ordersystem/assets/20488926/c9271e31-7f01-4706-bd01-06c62c98235d)

**Comment by yochan-Lab11** [comment]
@keinstn 
背景写真差し替え済です。ご対応ありがとうございます。クローズです。
